FROM node:16.20-alpine AS development
ENV NODE_ENV development

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm i

COPY . .

ENV PORT=3006
ENV PUBLIC_URL=./

EXPOSE 3006

CMD [ "npm", "start" ]
