# Fetching the latest node image on apline linux
FROM node:16.20-alpine AS builder

# Declaring env
ENV NODE_ENV development
ENV PORT=3000

# Setting up the work directory
WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

# Copying all the files in our project
COPY . .

# Building our application
RUN npm run build

EXPOSE $PORT

CMD ["npm", "run", "serverup"]

# # Fetching the latest nginx image
# FROM nginx

# # Copying built assets from builder
# COPY --from=builder /app/build /usr/share/nginx/html

# # Copying our nginx.conf
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# # Expose port
# EXPOSE 80

# # Start nginx
# CMD ["nginx", "-g", "daemon off;"]
